### Get list of users
GET http://localhost:8080/api/auth/users

### Create a new user
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "Jan Huang",
  "email": "janhuang@example.com",
  "password": "123456"
}


### Sign In 
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "email": "janhuang@example.com",
  "password": "123456"
}